policies:
  - name: policies.TreePolicy
    batch_size: 32
    epochs: 20
    rnn_size: 64
    featurizer:
      - name: MaxHistoryTrackerFeaturizer
        max_history: 38
        state_featurizer:
          - name: BinarySingleStateFeaturizer
